# Generated by Django 5.0.6 on 2024-05-16 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Woodworking', 'Woodworking'), ('Painting', 'Painting'), ('Knitting', 'Knitting'), ('Ceramics', 'Ceramics'), ('Jewelry Making', 'Jewelry Making'), ('Origami', 'Origami'), ('Embroidery', 'Embroidery'), ('Pottery', 'Pottery')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
