# Generated by Django 5.0.6 on 2024-05-13 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasehistory',
            name='product_name',
        ),
        migrations.AddField(
            model_name='purchasehistory',
            name='products',
            field=models.ManyToManyField(to='core.product'),
        ),
    ]
